spring:
  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
#    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 20
  batch:
    job:
      enabled: true
    jdbc:
      initialize-schema: always
  data:
    redis:
      host: localhost
      port: 6379
      database: 9
  flyway:
    batch: true

database:
  batch:
    jdbc-url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  primary:
    jdbc-url: jdbc:oracle:thin:@10.100.42.101:1521:IRKUDOS
    username: ADMIN
    password: admin00!!
    driver-class-name: oracle.jdbc.OracleDriver