services:
  postgres:
    image: postgres
    container_name: postgres
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
      TZ: Asia/Seoul

volumes:
  postgres-data: